FROM node:20-alpine3.19 AS base

#creating the stage which is responsible for build # Stage-1

FROM base AS builder


WORKDIR /home/build

COPY package*.json .
COPY tsconfig.json .


RUN npm install 

COPY src/ src/

RUN npm run build


#Stage 2 : for running the application 

FROM base AS runner 

WORKDIR /home/app


COPY --from=builder /home/build/dist dist/
COPY --from=builder /home/build/package*.json .


RUN npm install --omit=dev


CMD [ "npm","start" ]

