FROM node:20-alpine3.19 AS base

#creating the stage which is responsible for build # Stage-1

FROM base AS builder


WORKDIR /home/build

COPY package*.json .
COPY tsconfig.json .


RUN npm install 

COPY src/ src/

RUN npm run build


#Stage 2 : for running the application 

FROM base AS runner 

WORKDIR /home/app


COPY --from=builder /home/build/dist dist/
COPY --from=builder /home/build/package*.json .


RUN npm install --omit=dev

RUN addgroup --system --gid 10001 nodejs
RUN adduser --system --uid 1001 nodejs

USER nodejs

EXPOSE 8000
ENV PORT=8000


CMD [ "npm","start" ]

